#%RAML 0.8
title: Notes Example API
/openResource:
  displayName: JSON Typicode
  get:
    description: Get a resource
/external:
  displayName: External
  get:
    description: Get a resource